"""行為觀察 shim — 在 sandbox 跑 test 之前被 prepend。

設計（PLAN §22.5.5）：
- 攔截 socket / open / sqlite3 / urllib / httpx 的入口點
- 把每次呼叫寫到 JSON 檔（OBSERVER_LOG 環境變數指定路徑）
- atexit 時 flush，pytest 程序結束時保證落地
- 不阻擋（只觀察）—— 真要 enforce 是 U1 之後的事

這個 shim 是 Python 字串常數，由 SandboxRunner 寫到 sandbox 內變成 observer.py，
再透過 conftest.py 確保 import 早於使用者 code。
"""

from __future__ import annotations

# 注意：以下是 sandbox 內執行的程式碼，不是這個檔自己跑的
OBSERVER_SOURCE = r'''
"""Behavior observer — generated by sandbox harness. Don't edit."""
import atexit
import builtins
import json
import os
import socket as _socket_mod

_observations: list[dict] = []
_log_path = os.environ.get("OBSERVER_LOG", "/tmp/observer.json")


def _record(kind: str, **extra) -> None:
    """安全地記一筆 observation；任何錯誤都吞掉避免影響 SUT。"""
    try:
        _observations.append({"type": kind, **extra})
    except Exception:  # noqa: BLE001
        pass


# ── socket：抓任何網路呼叫的根源 ───────────────────────────────
_orig_socket = _socket_mod.socket


class _ObservedSocket(_orig_socket):  # type: ignore[misc]
    def __init__(self, *args, **kwargs):
        _record("socket", args=str(args), kwargs=str(kwargs))
        super().__init__(*args, **kwargs)


_socket_mod.socket = _ObservedSocket  # type: ignore[assignment]


# ── open：file system access ───────────────────────────────────
_orig_open = builtins.open


def _observed_open(file, mode="r", *args, **kwargs):
    try:
        path_str = str(file)
    except Exception:  # noqa: BLE001
        path_str = "<unprintable>"
    _record("open", path=path_str, mode=mode)
    return _orig_open(file, mode, *args, **kwargs)


builtins.open = _observed_open  # type: ignore[assignment]


# ── httpx / requests：常見 HTTP client（lazy attach，import 後才 hook）─
def _try_hook_httpx() -> None:
    try:
        import httpx  # type: ignore
    except ImportError:
        return
    if getattr(httpx, "_observed", False):
        return
    _orig_send = httpx.AsyncClient.send  # type: ignore[attr-defined]

    async def _observed_send(self, request, **kwargs):
        _record("httpx", method=str(request.method), url=str(request.url))
        return await _orig_send(self, request, **kwargs)

    httpx.AsyncClient.send = _observed_send  # type: ignore[assignment]
    httpx._observed = True  # type: ignore[attr-defined]


def _try_hook_requests() -> None:
    try:
        import requests  # type: ignore
    except ImportError:
        return
    if getattr(requests, "_observed", False):
        return
    _orig_request = requests.Session.request

    def _observed_request(self, method, url, **kwargs):
        _record("requests", method=str(method), url=str(url))
        return _orig_request(self, method, url, **kwargs)

    requests.Session.request = _observed_request  # type: ignore[assignment]
    requests._observed = True  # type: ignore[attr-defined]


_try_hook_httpx()
_try_hook_requests()


# ── flush ──────────────────────────────────────────────────────
def _flush() -> None:
    try:
        with _orig_open(_log_path, "w", encoding="utf-8") as f:
            json.dump(_observations, f, ensure_ascii=False)
    except Exception:  # noqa: BLE001
        pass


atexit.register(_flush)
'''
